baseURL = 'https://www.warrenkrewenki.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'salinger'


copyright = '2022 Warren Krewenki'
ignoreErrors = ["error-remote-getjson"]

[params]
DateFormat = "January 2006"

author = "Warren Krewenki"
description = "I'm a computer engineering student based in Modena, Italy. I like developing and designing random stuffs."
header = "<strong>Hi, I'm Warren. ðŸ‘‹ </strong>"
keywords = [ "developer", "coding", "maker"]
showHeaderOnHomepage = false
#googleAnalytics = ""
twemoji = true
text404 = "Since the page you were looking for seems like doesn't exist, we <strong>strongly</strong> suggest you to better investigate the URL and/or go back to the <a href=\"/\">home</a>. </br></br> <iframe src=\"https://giphy.com/embed/aCKMaeduKfFXG\" width=\"480\" height=\"480\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen></iframe>"
#fontawesomekitcode = ""


[permalinks]
  '/' = '/:slug/'
  'projects' = '/:slug/'

[[params.social]]
name = "github"
url = "https://github.com/krewenki"
icon = "fa fa-github"
before = "Reach me on "

[[params.social]]
name = "twitter"
url = "https://twitter.com/krewenki"
icon = "fa fa-twitter"
before = "and "

[[params.social]]
name = "email"
icon = "fa fa-envelope"
url = "mailto:contact@warrenkrewenki.com"
before = ", or drop me a line on"

[[params.social]]
name = "email"
icon = "fa fa-telegram"
url = "https://t.me/john"
before = "and on "
after = "."



[Menu]
[[Menu.Main]]
name = "Projects."
url = "/projects/"
weight = 1

[[Menu.Main]]
name = "Contact me."
url = "mailto:mail@mail.com"
weight = 2

[taxonomies]
	tag = "tags"
	category = "categories"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
